create table if not exists public.items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  category text not null default '기타',
  content text not null check (char_length(content) >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.items enable row level security;

drop policy if exists "users can read own items" on public.items;
drop policy if exists "users can insert own items" on public.items;
drop policy if exists "users can update own items" on public.items;
drop policy if exists "users can delete own items" on public.items;

create policy "users can read own items"
on public.items for select to authenticated
using (auth.uid() = user_id);

create policy "users can insert own items"
on public.items for insert to authenticated
with check (auth.uid() = user_id);

create policy "users can update own items"
on public.items for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users can delete own items"
on public.items for delete to authenticated
using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists items_set_updated_at on public.items;
create trigger items_set_updated_at
before update on public.items
for each row execute function public.set_updated_at();

create index if not exists items_user_created_idx
on public.items (user_id, created_at desc);
